services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: z
    ports:
      - "6020:443"
    volumes:
      - ./certs:/etc/nginx/certs:ro
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - my_network

networks:
  my_network:
    driver: bridge
