# Generated by Django 4.2 on 2026-05-21 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Passport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passport_number', models.CharField(max_length=100, verbose_name='Номер паспорта')),
                ('reservoir', models.CharField(blank=True, max_length=100, verbose_name='Резервуар')),
                ('measurement', models.CharField(blank=True, max_length=100, verbose_name='Замер')),
                ('manufacture_date', models.CharField(blank=True, max_length=100, verbose_name='Дата изготовления')),
                ('sample_collection_date', models.CharField(blank=True, max_length=100, verbose_name='Дата отбора образцов')),
                ('sample_arrival_date', models.CharField(blank=True, max_length=100, verbose_name='Дата поступления образцов')),
                ('test_date', models.CharField(blank=True, max_length=100, verbose_name='Дата проведения испытаний')),
                ('batch_number', models.CharField(blank=True, max_length=100, verbose_name='Партия №')),
                ('issue_date', models.CharField(blank=True, max_length=100, verbose_name='Дата выдачи паспорта')),
                ('actual_values', models.JSONField(default=dict, verbose_name='Фактические значения')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Паспорт',
                'verbose_name_plural': 'Паспорта',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Spravka',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spravka_number', models.CharField(max_length=100, verbose_name='Номер справки')),
                ('manufacture_date', models.CharField(blank=True, max_length=100, verbose_name='Дата изготовления / налива')),
                ('reservoir', models.CharField(blank=True, max_length=100, verbose_name='Резервуар')),
                ('measurement', models.CharField(blank=True, max_length=100, verbose_name='Замер')),
                ('wagon_count', models.CharField(blank=True, max_length=100, verbose_name='Количество вагон-цистерн')),
                ('wagon_numbers', models.TextField(blank=True, verbose_name='Номера вагон-цистерн')),
                ('sample_collection_date', models.CharField(blank=True, max_length=100, verbose_name='Дата отбора образцов')),
                ('issue_date', models.CharField(blank=True, max_length=100, verbose_name='Дата выдачи')),
                ('actual_values', models.JSONField(default=dict, verbose_name='Фактические значения')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Справка',
                'verbose_name_plural': 'Справки',
                'ordering': ['-created_at'],
            },
        ),
    ]
