# Generated by Django 4.2 on 2026-05-21 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passports_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='passport',
            name='document_content',
            field=models.TextField(blank=True, default='', verbose_name='Содержимое документа (HTML)'),
        ),
    ]
