# Generated by Django 4.2 on 2026-05-21 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passports_app', '0002_passport_document_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='PassportTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('category', models.CharField(blank=True, max_length=100, verbose_name='Категория')),
                ('content', models.TextField(blank=True, default='', verbose_name='Содержимое (HTML)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Шаблон паспорта',
                'verbose_name_plural': 'Шаблоны паспортов',
                'ordering': ['category', 'name'],
            },
        ),
    ]
