# Generated by Django 4.2 on 2026-05-21 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passports_app', '0003_passporttemplate'),
    ]

    operations = [
        migrations.AddField(
            model_name='passporttemplate',
            name='reservoir_type',
            field=models.CharField(blank=True, choices=[('', '—'), ('reservoir', 'Резервуар'), ('wagon', 'Вагон')], max_length=20, verbose_name='Резервуар / Вагон'),
        ),
    ]
