# Generated by Django 4.2 on 2026-05-21 11:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('passports_app', '0004_passporttemplate_reservoir_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='passport',
            name='batch_number',
        ),
        migrations.RemoveField(
            model_name='passport',
            name='document_content',
        ),
        migrations.RemoveField(
            model_name='passport',
            name='issue_date',
        ),
        migrations.RemoveField(
            model_name='passport',
            name='manufacture_date',
        ),
        migrations.RemoveField(
            model_name='passport',
            name='measurement',
        ),
        migrations.RemoveField(
            model_name='passport',
            name='passport_number',
        ),
        migrations.RemoveField(
            model_name='passport',
            name='reservoir',
        ),
        migrations.RemoveField(
            model_name='passport',
            name='sample_arrival_date',
        ),
        migrations.RemoveField(
            model_name='passport',
            name='sample_collection_date',
        ),
        migrations.RemoveField(
            model_name='passport',
            name='test_date',
        ),
        migrations.RemoveField(
            model_name='passporttemplate',
            name='content',
        ),
        migrations.AddField(
            model_name='passport',
            name='document_html',
            field=models.TextField(blank=True, default='', verbose_name='Документ (HTML)'),
        ),
        migrations.AddField(
            model_name='passport',
            name='field_values',
            field=models.JSONField(default=dict, verbose_name='Значения полей'),
        ),
        migrations.AddField(
            model_name='passport',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='passports_app.passporttemplate', verbose_name='Шаблон'),
        ),
        migrations.AddField(
            model_name='passporttemplate',
            name='footer_html',
            field=models.TextField(blank=True, default='', verbose_name='Подвал (HTML)'),
        ),
        migrations.AddField(
            model_name='passporttemplate',
            name='header_html',
            field=models.TextField(blank=True, default='', verbose_name='Шапка (HTML)'),
        ),
        migrations.AddField(
            model_name='passporttemplate',
            name='product_standard',
            field=models.CharField(blank=True, max_length=100, verbose_name="Стандарт (ГОСТ / O'zMSt)"),
        ),
        migrations.CreateModel(
            name='TemplateRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок')),
                ('name', models.CharField(max_length=400, verbose_name='Наименование показателя')),
                ('gost', models.CharField(blank=True, max_length=200, verbose_name='Метод контроля')),
                ('standard_value', models.CharField(blank=True, max_length=200, verbose_name='Значение по НД (OTP)')),
                ('standard_value_2', models.CharField(blank=True, max_length=200, verbose_name='Значение по НД (столбец 2)')),
                ('unit', models.CharField(blank=True, max_length=100, verbose_name='Единица / примечание')),
                ('is_section', models.BooleanField(default=False, verbose_name='Раздел (жирный заголовок без значения)')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rows', to='passports_app.passporttemplate')),
            ],
            options={
                'verbose_name': 'Строка таблицы',
                'verbose_name_plural': 'Строки таблицы',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='TemplateField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100, verbose_name='Ключ (placeholder)')),
                ('label', models.CharField(max_length=200, verbose_name='Название поля')),
                ('field_type', models.CharField(choices=[('text', 'Текст'), ('date', 'Дата'), ('number', 'Число'), ('select', 'Список'), ('textarea', 'Многострочный текст')], default='text', max_length=20, verbose_name='Тип')),
                ('options', models.JSONField(blank=True, default=list, verbose_name='Варианты (для select)')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок')),
                ('required', models.BooleanField(default=False, verbose_name='Обязательное')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='passports_app.passporttemplate')),
            ],
            options={
                'verbose_name': 'Поле шаблона',
                'verbose_name_plural': 'Поля шаблона',
                'ordering': ['order'],
                'unique_together': {('template', 'key')},
            },
        ),
    ]
