# Generated by Django 4.2 on 2026-07-24 06:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('passports_app', '0005_new_template_architecture'),
    ]

    operations = [
        migrations.AddField(
            model_name='passport',
            name='approval_status',
            field=models.CharField(choices=[('draft', 'Черновик'), ('pending_sttl', 'На подписи: Начальник СТТЛ'), ('pending_czl', 'На подписи: Начальник ЦЗЛ'), ('pending_dispatcher', 'На подписи: Диспетчер'), ('approved', 'Утверждён'), ('rejected', 'Отклонён')], default='draft', max_length=20, verbose_name='Статус согласования'),
        ),
        migrations.AddField(
            model_name='passport',
            name='czl_approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='passport',
            name='czl_approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='passport',
            name='czl_employee_slug',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='passport',
            name='dispatcher_approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='passport',
            name='dispatcher_approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='passport',
            name='dispatcher_employee_slug',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='passport',
            name='rejected_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='passport',
            name='rejected_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='passport',
            name='rejected_step',
            field=models.CharField(blank=True, choices=[('sttl', 'Начальник СТТЛ'), ('czl', 'Начальник ЦЗЛ'), ('dispatcher', 'Диспетчер')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='passport',
            name='rejection_comment',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='passport',
            name='sttl_approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='passport',
            name='sttl_approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='passport',
            name='sttl_employee_slug',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='passport',
            name='submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='passport',
            name='submitted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Отправил на подпись'),
        ),
    ]
