# Generated by Django 4.2 on 2026-07-27 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passports_app', '0007_passport_qr_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='passport',
            name='is_delete',
            field=models.BooleanField(default=False),
        ),
    ]
