import type { BenzinTableRow } from '../../rowTypes';

export const AI91_RESERVOIR_TABLE_ROWS: BenzinTableRow[] = [
  { key: 'a91r1_research', no: '1.', name: 'Октановое число по исследовательскому методу, не менее', gost: 'ГОСТ 8226', norm: '91,0', normOtr: '-', noRowSpan: 2, gostRowSpan: 1 },
  { key: 'a91r1_motor', no: '1.', name: 'октановое число по моторному методу, не менее', gost: 'ГОСТ 511', norm: '82,5', normOtr: '-' },
  { key: 'a91r2_lead', no: '2.', name: 'Массовая концентрация свинца, mg /dm³, не более', gost: 'ГОСТ 28828', norm: '10', normOtr: '10' },
  { key: 'a91r3_start', no: '3.', name: 'Фракционный состав: температура начала перегонки, °C, не ниже', gost: 'ГОСТ 2177', norm: '35', normOtr: '-', noRowSpan: 7, gostRowSpan: 7 },
  { key: 'a91r3_10', no: '3.', name: 'Пределы перегонки, 10%, не выше, °C', gost: 'ГОСТ 2177', norm: '75', normOtr: '-' },
  { key: 'a91r3_50', no: '3.', name: 'Пределы перегонки, 50%, не выше, °C', gost: 'ГОСТ 2177', norm: '120', normOtr: '-' },
  { key: 'a91r3_90', no: '3.', name: 'Пределы перегонки, 90%, не выше, °C', gost: 'ГОСТ 2177', norm: '190', normOtr: '-' },
  { key: 'a91r3_end', no: '3.', name: 'Конец кипения, °C, не выше', gost: 'ГОСТ 2177', norm: '215', normOtr: '-' },
  { key: 'a91r3_residue_vol', no: '3.', name: 'Объемная доля остатка в колбе, %, не более', gost: 'ГОСТ 2177', norm: '2,0', normOtr: '-' },
  { key: 'a91r3_loss', no: '3.', name: 'Остаток и потери, %, (по объёму) не более', gost: 'ГОСТ 2177', norm: '4,0', normOtr: '-' },
  { key: 'a91r4_pressure', no: '4.', name: 'Давление насыщенных паров бензина, кРа, не более', gost: 'ГОСТ 31874', norm: '66,7', normOtr: '35-80' },
  { key: 'a91r5_benzol', no: '5.', name: 'Объемная доля бензола, %, не более', gost: 'ГОСТ 31871', norm: '5', normOtr: '5' },
  { key: 'a91r6_resin', no: '6.', name: 'Массовая концентрация смол промытых растворителем, mg / 100 cm³, не более', gost: 'ГОСТ 32404', norm: '5', normOtr: '5' },
  { key: 'a91r7_induction', no: '7.', name: 'Индукционный период бензина, min, не менее', gost: 'ГОСТ 33903', norm: '450', normOtr: '-' },
  { key: 'a91r8_sulfur', no: '8.', name: 'Массовая доля серы, mg/kg, не более', gost: 'ГОСТ 19121', norm: '500', normOtr: '500' },
  { key: 'a91r9_copper', no: '9.', name: 'Испытание на медной пластинке (3h при 50 °C)', gost: 'ГОСТ32329', norm: 'Класс 1', normOtr: '-' },
  { key: 'a91r10_density20', no: '10.', name: 'Плотность при 20 °C, kg/m³', gost: 'ГОСТ 3900', norm: 'Не нормируется. определение обязательно', normOtr: '-', noRowSpan: 2, gostRowSpan: 2, gostMarginTopOverride: 18 },
  { key: 'a91r10_density15', no: '10.', name: 'Плотность при 15 °C, kg/m³ не менее', gost: 'ГОСТ 3900', norm: '725,0', normOtr: '-' },
  { key: 'a91r11_acids', no: '11.', name: 'Содержание водорастворимых кислот и щелочей', gost: 'ГОСТ 6307', norm: 'отсутствие', normOtr: '-' },
  { key: 'a91r12_mechanical', no: '12.', name: 'Содержание механических примесей и воды', gost: 'Визуально 7.3 нас. ст', norm: 'отсутствие', normOtr: '-' },
  { key: 'a91r13_appearance', no: '13.', name: 'Внешний вид', gost: 'Визуально 7.3 нас. ст', norm: 'Чистый, прозрачный', normOtr: '-', gostRowSpan: 1 },
  { key: 'a91r14_manganese', no: '14.', name: 'Массовая концентрация марганца. mg /dm³ не более', gost: 'ASTM D 3831', norm: 'отсутствие', normOtr: 'отсутствие' },
  { key: 'a91r15_iron', no: '15.', name: 'Массовая концентрация железа. g /dm³ не более', gost: 'ГОСТ 32514', norm: 'отсутствие', normOtr: 'отсутствие' },
];

export const AI91_WAGON_TABLE_ROWS: BenzinTableRow[] = [
  { key: 'a91w1_research', no: '1', name: 'Октановое число по исследовательскому методу, не менее', gost: 'ГОСТ 8226', norm: '91,0', normOtr: '91,0', noRowSpan: 2, gostRowSpan: 1 },
  { key: 'a91w1_motor', no: '1', name: 'октановое число по моторному методу, не менее', gost: 'ГОСТ 511', norm: '82,5', normOtr: '82,5' },
  { key: 'a91w2_lead', no: '2', name: 'Массовая концентрация свинца, mg /dm³, не более', gost: 'ГОСТ 28828', norm: '10', normOtr: '10' },
  { key: 'a91w3_start', no: '3', name: 'Фракционный состав: температура начала перегонки, °C, не ниже', gost: 'ГОСТ 2177', norm: '35', normOtr: '-', noRowSpan: 7, gostRowSpan: 7 },
  { key: 'a91w3_10', no: '3', name: 'Пределы перегонки, 10%, не выше, °C', gost: 'ГОСТ 2177', norm: '75', normOtr: '-' },
  { key: 'a91w3_50', no: '3', name: 'Пределы перегонки, 50%, не выше, °C', gost: 'ГОСТ 2177', norm: '120', normOtr: '-' },
  { key: 'a91w3_90', no: '3', name: 'Пределы перегонки, 90%, не выше, °C', gost: 'ГОСТ 2177', norm: '190', normOtr: '-' },
  { key: 'a91w3_end', no: '3', name: 'Конец кипения, °C, не выше', gost: 'ГОСТ 2177', norm: '215', normOtr: '-' },
  { key: 'a91w3_residue_vol', no: '3', name: 'Объемная доля остатка в колбе, %, не более', gost: 'ГОСТ 2177', norm: '2,0', normOtr: '-' },
  { key: 'a91w3_loss', no: '3', name: 'Остаток и потери, %, (по объёму) не более', gost: 'ГОСТ 2177', norm: '4,0', normOtr: '-' },
  { key: 'a91w4_pressure', no: '4', name: 'Давление насыщенных паров бензина, кРа, не более', gost: 'ГОСТ 31874', norm: '66,7', normOtr: '35-80' },
  { key: 'a91w5_benzol', no: '5', name: 'Объемная доля бензола % не более', gost: 'ГОСТ 31871', norm: '5', normOtr: '5' },
  { key: 'a91w6_resin', no: '6', name: 'Массовая концентрация смол промытых растворителем mg / 100 cm³ не более', gost: 'ГОСТ 32329', norm: '5', normOtr: '5' },
  { key: 'a91w7_induction', no: '7', name: 'Индукционный период бензина min, не менее', gost: 'ГОСТ 33903', norm: '450', normOtr: '-' },
  { key: 'a91w8_sulfur', no: '8', name: 'Массовая доля серы, mg/kg, не более', gost: 'ГОСТ 19121', norm: '500', normOtr: '500' },
  { key: 'a91w9_copper', no: '9', name: 'Испытание на медной пластинке (3h при 50 °C)', gost: 'ГОСТ32329', norm: 'Класс 1', normOtr: '-' },
  { key: 'a91w10_density20', no: '10', name: 'Плотность при 20 °C, kg/m³', gost: 'ГОСТ 3900', norm: 'Не нормируется определение обязательно', normOtr: '-', noRowSpan: 2, gostRowSpan: 2, gostMarginTopOverride: 18 },
  { key: 'a91w10_density15', no: '10', name: 'Плотность при 15 °C, kg/m³ не менее', gost: 'ГОСТ 3900', norm: '725,0', normOtr: '-' },
  { key: 'a91w11_acids', no: '11', name: 'Содержание водорастворимых кислот и щелочей', gost: 'ГОСТ 6307', norm: 'отсутствие', normOtr: '-' },
  { key: 'a91w12_mechanical', no: '12', name: 'Содержание механических примесей и воды', gost: 'Визуально 7.3 нас. ст', norm: 'отсутствие', normOtr: '-' },
  { key: 'a91w13_appearance', no: '13', name: 'Внешний вид', gost: 'Визуально 7.3 нас. ст', norm: 'Чистый, прозрачный', normOtr: '-', gostRowSpan: 1 },
  { key: 'a91w14_manganese', no: '14', name: 'Массовая концентрация марганца. mg /dm³ не более', gost: 'ASTM D 3831', norm: 'отсутствие', normOtr: 'отсутствие' },
  { key: 'a91w15_iron', no: '15', name: 'Массовая концентрация железа. g /dm³ не более', gost: 'ГОСТ 32514', norm: 'отсутствие', normOtr: 'отсутствие' },
];
