# Generated by Django 4.2 on 2026-07-24 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0036_item_affects_stock'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='positionpperenewalrule',
            options={'ordering': ['department_name', 'position_name', 'ppeproduct__name', 'id'], 'verbose_name': 'Норма выдачи СИЗ по должности', 'verbose_name_plural': 'Нормы выдачи СИЗ по должностям'},
        ),
        migrations.RemoveField(
            model_name='historicalemployee',
            name='headdress_size',
        ),
        migrations.AddField(
            model_name='responsibleperson',
            name='employee_slug',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Slug сотрудника (employee_service)'),
        ),
    ]
