# Generated by Django 4.2 on 2026-08-05 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_replace_laboratory_manager_with_role_heads'),
    ]

    operations = [
        migrations.AddField(
            model_name='rolepageaccess',
            name='can_view_passports',
            field=models.BooleanField(default=True),
        ),
    ]
